
package ui;

import database.DataBaseHandler;
import model.*;
import exceptions.InputException;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 *
 * @author alansmacbook
 *
 *
 */
public class GUI extends javax.swing.JFrame {
    
    RegisterForm rf;
    DetailsTable dt;
    Rental r;
    ReturnReceipt rr;
    Reservation res;
    DataBaseHandler database;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        database = new DataBaseHandler();// asynchrony??????

        try {
            Image sherwyb = new ImageIcon(this.getClass().getResource("/resources/icon.png")).getImage();
            //this.setIconImage(sherwyb);
            //Application.getApplication().setDockIconImage(sherwyb);
        } catch (Exception e) {
            System.out.println("sad sherwyb");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        TabbedPane = new javax.swing.JTabbedPane();
        CustomerPanel = new javax.swing.JPanel();
        SearchType = new javax.swing.JTextField();
        SearchLocation = new javax.swing.JTextField();
        SearchFrom = new javax.swing.JTextField();
        SearchTo = new javax.swing.JTextField();
        SearchExecute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarSearchTable = new javax.swing.JTable();
        ReserveName = new javax.swing.JTextField();
        ReserveLicence = new javax.swing.JTextField();
        RequestReserveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ReserveType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ReserveLocation = new javax.swing.JTextField();
        ReservePDate = new javax.swing.JTextField();
        ReservePTime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ReserveRTime = new javax.swing.JTextField();
        ReserveRDate = new javax.swing.JTextField();
        NewRegisterButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        ClerkPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ReturnButton = new javax.swing.JButton();
        CompanyRentalReport = new javax.swing.JButton();
        LocationRentalReport = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        RentalReportLocation = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ReturnReportLocation = new javax.swing.JTextField();
        LocationReturnReport = new javax.swing.JButton();
        CompanyReturnReport = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ReturnRentID = new javax.swing.JTextField();
        ReturnDate = new javax.swing.JTextField();
        ReturnGas = new javax.swing.JTextField();
        ReturnOdometer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ClerkRentalConfirmation = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        FindReservationButton = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        NewRentalRTime = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NewRentalRDate = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        NewRentalPTime = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        NewRentalPDate = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        NewRentalLocation = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        NewRentalType = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        NewRentalLicence = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        NewRentalName = new javax.swing.JTextField();
        RequestRental = new javax.swing.JButton();
        TablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTable = new javax.swing.JTable();
        TableDropdown = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TupleEntry = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        InsertButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Car Database Project!");

        SearchTo.setToolTipText("");

        SearchExecute.setText("Search");
        SearchExecute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                try {
                    SearchExecuteMouseClicked(evt);
                } catch (InputException e) {
                    ErrorTemplate er = new ErrorTemplate(e.getMessage());

                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Make a Reservation");

        CarSearchTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Car Type", "Location", "From", "To", "Count"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarSearchTable.getTableHeader().setReorderingAllowed(false);
        CarSearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CarSearchTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(CarSearchTable);

        RequestReserveButton.setText("Request Reservation");
        RequestReserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestReserveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("New? Register Here");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Customer Details");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setText("Reservation Details");

        jLabel8.setText("Car Type");

        jLabel9.setText("Location");

        jLabel10.setText("Pickup Date");

        jLabel11.setText("Pickup Time");

        jLabel12.setText("Return Date");

        jLabel13.setText("Return Time");

        NewRegisterButton.setText("Register");
        NewRegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewRegisterButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Name");

        jLabel15.setText("License Number");

        jLabel39.setText("Car Type");

        jLabel40.setText("Location");

        jLabel41.setText("From Date");

        jLabel42.setText("To Date");

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
                CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane1)
                                                .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel39)
                                                        .addGap(71, 71, 71)
                                                        .addComponent(jLabel40)
                                                        .addGap(72, 72, 72)
                                                        .addComponent(jLabel41)
                                                        .addGap(61, 61, 61)
                                                        .addComponent(jLabel42)
                                                        .addGap(162, 162, 162)))
                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                .addComponent(SearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchTo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SearchExecute)))
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(NewRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94))
                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                                .addGap(96, 96, 96)
                                                                .addComponent(jLabel4))
                                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                                .addGap(39, 39, 39)
                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                        .addComponent(jLabel9)
                                                                                                        .addComponent(jLabel10)
                                                                                                        .addComponent(jLabel11)
                                                                                                        .addComponent(jLabel8))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(ReserveType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(ReserveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(ReservePDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(ReservePTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                        .addComponent(jLabel12)
                                                                                                        .addComponent(jLabel13))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(ReserveRDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(ReserveRTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                        .addComponent(jLabel14)
                                                                                                        .addComponent(jLabel15))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                                        .addComponent(ReserveName)
                                                                                                        .addComponent(ReserveLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPanelLayout.createSequentialGroup()
                                                                                        .addComponent(jLabel7)
                                                                                        .addGap(76, 76, 76)))
                                                                        .addComponent(RequestReserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(43, Short.MAX_VALUE))
                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel5))
                                                        .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        CustomerPanelLayout.setVerticalGroup(
                CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel39)
                                        .addComponent(jLabel40)
                                        .addComponent(jLabel41)
                                        .addComponent(jLabel42))
                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(NewRegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel14))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel15))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReservePDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReservePTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveRDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReserveRTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                .addGap(18, 18, 18)
                                                .addComponent(RequestReserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(59, Short.MAX_VALUE))
                                        .addGroup(CustomerPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(SearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchExecute))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1))))
        );

        SearchType.getAccessibleContext().setAccessibleName("");

        TabbedPane.addTab("Customer", CustomerPanel);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Generate a Report");

        ReturnButton.setText("Return Car");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        CompanyRentalReport.setText("Company Wide Rental Report");
        CompanyRentalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyRentalReportActionPerformed(evt);
            }
        });

        LocationRentalReport.setText("Rentals for One Location");
        LocationRentalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationRentalReportActionPerformed(evt);
            }
        });

        jLabel18.setText("Location:");

        jLabel19.setText("Location:");

        LocationReturnReport.setText("Returns for One Location");
        LocationReturnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationReturnReportActionPerformed(evt);
            }
        });

        CompanyReturnReport.setText("Company Wide Return Report");
        CompanyReturnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyReturnReportActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel23.setText("Return a Car");

        jLabel24.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel24.setText("Rent a Car");

        jLabel25.setText("Rent ID");

        jLabel26.setText("Date");

        jLabel27.setText("Odometer");

        jLabel28.setText("Gas Tank");

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel16.setText("With Reservation");

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel17.setText("No Reservation");

        jLabel30.setText("Confirmation Number");

        FindReservationButton.setText("Find Reservation");
        FindReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindReservationButtonActionPerformed(evt);
            }
        });

        jLabel31.setText("Return Time");

        jLabel32.setText("Return Date");

        jLabel33.setText("Pickup Time");

        jLabel34.setText("Pickup Date");

        jLabel35.setText("Location");

        jLabel36.setText("Car Type");

        jLabel37.setText("License Number");

        jLabel38.setText("Name");

        RequestRental.setText("Request Rental");
        RequestRental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestRentalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClerkPanelLayout = new javax.swing.GroupLayout(ClerkPanel);
        ClerkPanel.setLayout(ClerkPanelLayout);
        ClerkPanelLayout.setHorizontalGroup(
                ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClerkPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClerkPanelLayout.createSequentialGroup()
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel35)
                                                                        .addComponent(jLabel34)
                                                                        .addComponent(jLabel33)
                                                                        .addComponent(jLabel36))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(NewRentalType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(NewRentalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(NewRentalPDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(NewRentalPTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel32)
                                                                        .addComponent(jLabel31))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(NewRentalRDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(NewRentalRTime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel38)
                                                                        .addComponent(jLabel37))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(NewRentalName)
                                                                        .addComponent(NewRentalLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel30)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(ClerkRentalConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                                                .addComponent(jLabel26))
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClerkPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel25))
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel17)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel28))
                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                .addGap(77, 77, 77)
                                                                .addComponent(FindReservationButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabel27)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClerkPanelLayout.createSequentialGroup()
                                                .addComponent(ReturnRentID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(56, 56, 56)
                                                .addComponent(CompanyRentalReport, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ReturnGas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ReturnOdometer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ReturnButton))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClerkPanelLayout.createSequentialGroup()
                                                                        .addComponent(jLabel18)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(RentalReportLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                                                .addGap(14, 14, 14)
                                                                                .addComponent(jLabel19)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(ReturnReportLocation))
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(CompanyReturnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                                                        .addComponent(LocationReturnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(LocationRentalReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(63, 63, 63))
                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(jLabel24)
                                                .addGap(216, 216, 216)
                                                .addComponent(jLabel23))
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(RequestRental, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClerkPanelLayout.setVerticalGroup(
                ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CompanyRentalReport)
                                        .addComponent(jLabel25)
                                        .addComponent(ReturnRentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addComponent(LocationRentalReport)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel18)
                                                        .addComponent(RentalReportLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(CompanyReturnReport)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LocationReturnReport)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel19)
                                                        .addComponent(ReturnReportLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel26))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReturnOdometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel27))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ReturnGas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel28))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ReturnButton))
                                        .addGroup(ClerkPanelLayout.createSequentialGroup()
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ClerkRentalConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel30))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(FindReservationButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel38))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel37))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel36))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel35))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalPDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel34))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalPTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel33))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalRDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel32))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(ClerkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(NewRentalRTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel31))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RequestRental)
                                .addContainerGap(66, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Clerk", ClerkPanel);

        TableTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane2.setViewportView(TableTable);

        // TODO add tables here
        TableDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Rent", "Reservation", "Return", "Vehicle", "VehicleType" }));
        TableDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableDropdownActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel20.setText("Table:");

        // TODO add instructions for deletion and update here
        jLabel21.setText("Insert Customer: (cellphone, name, address, dlicense) | Delete Return: (rid)");

        TupleEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TupleEntryActionPerformed(evt);
            }
        });

        jLabel22.setText("Tuple:");

        InsertButton.setText("Insert");
        InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
                TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TablePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(TablePanelLayout.createSequentialGroup()
                                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel20)
                                                        .addComponent(TableDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(22, 22, 22)
                                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(TablePanelLayout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(TupleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(InsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                                                .addContainerGap())))
        );
        TablePanelLayout.setVerticalGroup(
                TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TablePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InsertButton))
                                .addGap(3, 3, 3)
                                .addGroup(TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TableDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TupleEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel22)
                                        .addComponent(DeleteButton))
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        TabbedPane.addTab("Tables", TablePanel);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel3.setText("By Sherwyn, Jacques, and Alan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>





    private void SearchExecuteMouseClicked(java.awt.event.MouseEvent evt) throws InputException {
        String type = SearchType.getText();
        String location = SearchLocation.getText();
        String from = SearchFrom.getText();
        String to = SearchTo.getText();

        //TODO this should have a return type, and should shove that return value into the table after processing
        ArrayList<Vehicle> result = database.searchCars(type,location,from,to);


    }

    //register new customer, text from ReserveName, ReserveLicense
    //this will need to insert in to db
    private void NewRegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (rf != null) {rf.dispose();}
        rf = new RegisterForm(database);
    }

    //queries for a reservable vehicle, error handling for none found, text from Reserve+{Type,Location,PDate,PTime,RDate,RTime}
    //do a query, if it comes back good pick first index i guess and launch a receipt, otherwise throw error message
    private void RequestReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (res != null) {res.dispose();}
        try {
            String name = ReserveName.getText();
            String license = ReserveLicence.getText();
            String type = ReserveType.getText();
            String location = ReserveLocation.getText();
            String pdate = ReservePDate.getText();
            String ptime = ReservePTime.getText();
            String rdate = ReserveRDate.getText();
            String rtime = ReserveRTime.getText();

            res = new Reservation(database,name,license,type,location,pdate,ptime,rdate,rtime);
        } catch (Exception e) {
            ErrorTemplate er = new ErrorTemplate(e.getMessage());
        }
    }

    //opens sublist for details of cars when mouse is pressed on table entry
    //i think the best approach is to put an array of data into the detailstable constructor along with the string at the top
    //use
    private void CarSearchTableMousePressed(java.awt.event.MouseEvent evt) {
        if (dt != null) {dt.dispose();}


        dt = new DetailsTable();
    }

    //clerk returns a car, text from Return+{RentID,Date,Odometer,Gas}
    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (rr != null) {rr.dispose();}
            String returnid = ReturnRentID.getText();
            String date = ReturnDate.getText();
            String odometer = ReturnOdometer.getText();
            String gas = ReturnGas.getText();
            rr = new ReturnReceipt(database,returnid,date,odometer,gas);

        } catch (Exception e) {
            ErrorTemplate er = new ErrorTemplate(e.getMessage());
        }
    }

    private void CompanyRentalReportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void LocationRentalReportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CompanyReturnReportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void LocationReturnReportActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TupleEntryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // Inserts into the Customer table
        String attributes = TupleEntry.getText();
        List<String> insertList = Arrays.asList(attributes.split("\\s*,\\s*"));
        database.addCustomer(insertList.get(0), insertList.get(1), insertList.get(2), insertList.get(3));
    }

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {
        database.deleteReturn(Integer.parseInt(TupleEntry.getText()));
    }

    // TODO update action goes somewhere here

    // TODO Make sure this display table function works
    private void TableDropdownActionPerformed(java.awt.event.ActionEvent evt){
        String table = String.valueOf(TableDropdown.getSelectedItem());
        if(table == "Customer") {
            DisplayCustomerTable();
        } else if (table == "Rent") {
            DisplayRentTable();
        } else if (table == "Reservation") {
            DisplayReservationTable();
        } else if (table == "Return") {
            DisplayReturnTable();
        } else if (table == "Vehicle") {
            DisplayVehicleTable();
        } else if (table == "VehicleType") {
            DisplayVehicleTypeTable();
        }
    }

    private void DisplayCustomerTable() {
        String colNames[] = {"cellphone", "name", "address", "dlicense"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<Customer> customers = database.getCustomers();
        for(int x = 0, y = customers.size(); x < y; x++) {
            Customer c = customers.get(x);
            dtm.addRow(c.getData());
        }
        TableTable.setModel(dtm);
    }

    private void DisplayRentTable() {
        String colNames[] = {"rid", "vlicense", "dlicense", "fromDate", "toDate", "odometer", "cardName", "cardNo", "expDate", "confNo"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<Rent> rentals = database.getRents();
        for(int x = 0, y = rentals.size(); x < y; x++) {
            Rent r = rentals.get(x);
            dtm.addRow(r.getData());
        }
        TableTable.setModel(dtm);
    }

    private void DisplayReservationTable() {
        String colNames[] = {"confNo", "vtname", "dlicense", "fromDate", "toDate"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<model.Reservation> reservations = database.getReservations();
        for(int x = 0, y = reservations.size(); x < y; x++) {
            model.Reservation r = reservations.get(x);
            dtm.addRow(r.getData());
        }
        TableTable.setModel(dtm);
    }

    private void DisplayReturnTable() {
        String colNames[] = {"rid", "rDate", "odometer", "fullTank", "value"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<Return> returns = database.getReturns();
        for(int x = 0, y = returns.size(); x < y; x++) {
            Return r = returns.get(x);
            dtm.addRow(r.getData());
        }
        TableTable.setModel(dtm);
    }

    private void DisplayVehicleTable() {
        String colNames[] = {"vlicense", "make", "model", "year", "color", "odometer", "status", "vtname", "location", "city"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<Vehicle> vehicles = database.getVehicles();
        for(int x = 0, y = vehicles.size(); x < y; x++) {
            Vehicle v = vehicles.get(x);
            dtm.addRow(v.getData());
        }
        TableTable.setModel(dtm);
    }

    private void DisplayVehicleTypeTable() {
        String colNames[] = {"vtname", "features", "wrate", "drate", "hrate", "wirate", "dirate", "hirate", "krate"};
        DefaultTableModel dtm = new DefaultTableModel(null, colNames);
        java.util.List<VehicleType> types = database.getVehicleTypes();
        for(int x = 0, y = types.size(); x < y; x++) {
            VehicleType vt = types.get(x);
            dtm.addRow(vt.getData());
        }
        TableTable.setModel(dtm);
    }




    private void FindReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (r != null) {r.dispose();}
        try {
            String confNo = ClerkRentalConfirmation.getText();
            r = new Rental(database,confNo);
        } catch (Exception e) {
            ErrorTemplate er = new ErrorTemplate(e.getMessage());
        }

    }

    private void RequestRentalActionPerformed(java.awt.event.ActionEvent evt) {
        if (r != null) {r.dispose();}
        try {
            String name = NewRentalName.getText();
            String licnece = NewRentalLicence.getText();
            String type = NewRentalType.getText();
            String location = NewRentalLocation.getText();
            String pdate = NewRentalPDate.getText();
            String ptime = NewRentalPTime.getText();
            String rdate = NewRentalRDate.getText();
            String rtime = NewRentalRTime.getText();

            //TODO i died here

            r = new Rental(database);

        } catch (Exception e) {
            ErrorTemplate er = new ErrorTemplate(e.getMessage());
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    private javax.swing.JTable CarSearchTable;
    private javax.swing.JPanel ClerkPanel;
    private javax.swing.JTextField ClerkRentalConfirmation;
    private javax.swing.JButton CompanyRentalReport;
    private javax.swing.JButton CompanyReturnReport;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton FindReservationButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton LocationRentalReport;
    private javax.swing.JButton LocationReturnReport;
    private javax.swing.JButton NewRegisterButton;
    private javax.swing.JTextField NewRentalLicence;
    private javax.swing.JTextField NewRentalLocation;
    private javax.swing.JTextField NewRentalName;
    private javax.swing.JTextField NewRentalPDate;
    private javax.swing.JTextField NewRentalPTime;
    private javax.swing.JTextField NewRentalRDate;
    private javax.swing.JTextField NewRentalRTime;
    private javax.swing.JTextField NewRentalType;
    private javax.swing.JTextField RentalReportLocation;
    private javax.swing.JButton RequestRental;
    private javax.swing.JButton RequestReserveButton;
    private javax.swing.JTextField ReserveLicence;
    private javax.swing.JTextField ReserveLocation;
    private javax.swing.JTextField ReserveName;
    private javax.swing.JTextField ReservePDate;
    private javax.swing.JTextField ReservePTime;
    private javax.swing.JTextField ReserveRDate;
    private javax.swing.JTextField ReserveRTime;
    private javax.swing.JTextField ReserveType;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JTextField ReturnDate;
    private javax.swing.JTextField ReturnGas;
    private javax.swing.JTextField ReturnOdometer;
    private javax.swing.JTextField ReturnRentID;
    private javax.swing.JTextField ReturnReportLocation;
    private javax.swing.JButton SearchExecute;
    private javax.swing.JTextField SearchFrom;
    private javax.swing.JTextField SearchLocation;
    private javax.swing.JTextField SearchTo;
    private javax.swing.JTextField SearchType;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JComboBox<String> TableDropdown;
    private javax.swing.JPanel TablePanel;
    private javax.swing.JTable TableTable;
    private javax.swing.JTextField TupleEntry;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
}
