package ui;

public class RentalReceipt extends javax.swing.JFrame {

    /**
     * Creates new form RentalReceipt
     */
    public RentalReceipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        RDPTime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        RDRDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ConfirmRentalButton = new javax.swing.JButton();
        RDName = new javax.swing.JLabel();
        RDDLicense = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RDType = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RDLocation = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RDPDATE = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        RDRTime = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RDRID = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RDCardName = new javax.swing.JLabel();
        RDExpDate = new javax.swing.JLabel();
        RDCardNum = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RDCarLicence = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Pickup Time");

        RDPTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDPTime.setText("<PTIME>");

        jLabel12.setText("Return Date");

        RDRDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDRDate.setText("<RDATE>");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Rental Receipt");

        jLabel2.setText("Name");

        jLabel3.setText("Drivers Licence");

        ConfirmRentalButton.setText("Close");
        ConfirmRentalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmRentalButtonActionPerformed(evt);
            }
        });

        RDName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDName.setText("<NAME>");

        RDDLicense.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDDLicense.setText("<DLICENSE>");

        jLabel8.setText("Car Type");

        RDType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDType.setText("<TYPE>");

        jLabel9.setText("Location");

        RDLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDLocation.setText("<LOCATION>");

        jLabel10.setText("Pickup Date");

        RDPDATE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDPDATE.setText("<PDATE>");

        jLabel15.setText("Return Time");

        RDRTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDRTime.setText("<RTIME>");

        jLabel16.setText("Rental ID");

        RDRID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDRID.setText("<RID>");

        jLabel17.setText("Card Name");

        jLabel13.setText("Credit Card #");

        jLabel18.setText("Credit Card Exp");

        RDCardName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDCardName.setText("<CARDNAME>");

        RDExpDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDExpDate.setText("<CARDEXP>");

        RDCardNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDCardNum.setText("<CARDNUM>");

        jLabel14.setText("Card Licence");

        RDCarLicence.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        RDCarLicence.setText("<CLICENCE>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(132, 132, 132)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(RDName, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDLocation, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDType, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDPDATE, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDPTime, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDRDate, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDDLicense, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDRTime, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDRID, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDCardName, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDExpDate, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDCardNum, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RDCarLicence, javax.swing.GroupLayout.Alignment.LEADING)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(ConfirmRentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(RDName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(RDDLicense))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(RDType))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(RDCarLicence))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(RDLocation))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(RDPDATE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(RDPTime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(RDRDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(RDRTime))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(RDRID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(RDCardNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(RDExpDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(RDCardName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConfirmRentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void ConfirmRentalButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton ConfirmRentalButton;
    private javax.swing.JLabel RDCarLicence;
    private javax.swing.JLabel RDCardName;
    private javax.swing.JLabel RDCardNum;
    private javax.swing.JLabel RDDLicense;
    private javax.swing.JLabel RDExpDate;
    private javax.swing.JLabel RDLocation;
    private javax.swing.JLabel RDName;
    private javax.swing.JLabel RDPDATE;
    private javax.swing.JLabel RDPTime;
    private javax.swing.JLabel RDRDate;
    private javax.swing.JLabel RDRID;
    private javax.swing.JLabel RDRTime;
    private javax.swing.JLabel RDType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration
}

