/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alansmacbook
 */

package ui;


import database.DataBaseHandler;
import exceptions.InputException;

public class ReturnReceipt extends javax.swing.JFrame {

    DataBaseHandler database;

    /**
     * Creates new form ReturnReceipt
     */
    public ReturnReceipt(DataBaseHandler db, String rentid, String date, String odometer, String gas) throws InputException {
        initComponents();
        //db.query to prove existence, if not then throw here
        //do db stuff to fix statuses and stuff, and get additional data needed
        database = db;
        if (rentid.equals("") || date.equals("") || odometer.equals("") || gas.equals("")) {throw new InputException("Missing inputs!");}
        String[] receiptInfo = db.handleReturn(Integer.parseInt(rentid), date, Integer.parseInt(odometer), Boolean.parseBoolean(gas));
        RRRID.setText(receiptInfo[0]);
        RRRDATE.setText(receiptInfo[1]);
//        RRWRATE.setText();
//        RRDRATE.setText();
//        RRHRATE.setText();
//        RRWEEKS.setText();
//        RRDAYS.setText();
        RRHOURS.setText(receiptInfo[3]);
        RRTOTAL.setText(receiptInfo[4]);


        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RRRID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RRRDATE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RRRTIME = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RRWRATE = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RRDRATE = new javax.swing.JLabel();
        RRHRATE = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        RRDAYS = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RRWEEKS = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RRHOURS = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        RRTOTAL = new javax.swing.JLabel();
        RRClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Return Receipt");

        jLabel2.setText("Rent ID");

        RRRID.setText("<RID>");

        jLabel4.setText("Return Date");

        RRRDATE.setText("<RDATE>");

        jLabel6.setText("Return Time");

        RRRTIME.setText("<RTIME>");

        jLabel8.setText("Weekly Rate");

        RRWRATE.setText("<WRATE>");

        jLabel10.setText("Daily Rate");

        RRDRATE.setText("<DRATE>");

        RRHRATE.setText("<HRATE>");

        jLabel13.setText("Hourly Rate");

        jLabel14.setText("Days");

        RRDAYS.setText("<DAYS>");

        jLabel16.setText("Weeks");

        RRWEEKS.setText("<WEEKS>");

        jLabel18.setText("Hours");

        RRHOURS.setText("<HOURS>");

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel20.setText("Total Cost");

        RRTOTAL.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        RRTOTAL.setText("<TOTAL>");

        RRClose.setText("Close");
        RRClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RRCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RRHRATE)
                            .addComponent(RRWEEKS)
                            .addComponent(RRDAYS)
                            .addComponent(RRHOURS)
                            .addComponent(RRTOTAL))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RRRID)
                                    .addComponent(RRRDATE)
                                    .addComponent(RRRTIME)
                                    .addComponent(RRDRATE)
                                    .addComponent(RRWRATE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel20))
                                .addGap(99, 99, 99)))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RRClose)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RRRID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RRRDATE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RRRTIME))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RRWRATE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(RRDRATE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(RRHRATE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(RRWEEKS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(RRDAYS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(RRHOURS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(RRTOTAL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(RRClose)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RRCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }


    private javax.swing.JButton RRClose;
    private javax.swing.JLabel RRDAYS;
    private javax.swing.JLabel RRDRATE;
    private javax.swing.JLabel RRHOURS;
    private javax.swing.JLabel RRHRATE;
    private javax.swing.JLabel RRRDATE;
    private javax.swing.JLabel RRRID;
    private javax.swing.JLabel RRRTIME;
    private javax.swing.JLabel RRTOTAL;
    private javax.swing.JLabel RRWEEKS;
    private javax.swing.JLabel RRWRATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
}
